data:
  train_path: './data/train.csv'
  test_path: './data/test.csv'
  submission_path: './data/sample_submission.csv'
  output_path: './data/submission'
  label_column: '채무 불이행 여부'

features:
  # 기본값을 사용하려면 아래 설정들을 생략해도 됩니다
  nominal_columns:
    - 주거 형태
    - 대출 목적
    - 대출 상환 기간
  
  ordinal_columns:
    - 현재 직장 근속 연수:
        - 1년 미만
        - 1년
        - 2년
        - 3년
        - 4년
        - 5년
        - 6년
        - 7년
        - 8년
        - 9년
        - 10년 이상

  # 참고용 numerical 컬럼들 (코드에서는 자동으로 계산됨)
  numerical_discrete:
    - 개설된 신용계좌 수
    - 신용 문제 발생 횟수
    - 마지막 연체 이후 경과 개월 수
    - 개인 파산 횟수
    - 신용 점수
    - 대출 목적_고위험
    - 근속 연수
    - 장기 근속 여부
    - 최근 연체 있음
    - 파산 경험 여부

  numerical_continuous:
    - 연간 소득
    - 체납 세금 압류 횟수
    - 신용 거래 연수
    - 최대 신용한도
    - 현재 대출 잔액
    - 현재 미상환 신용액
    - 월 상환 부채액
    - 자산 # 1
    - 대출 이자율
    - 대출 비율
    - 신용 비율
    - 주거 형태 채무 불이행률
    - 대출 목적 채무 불이행률
    - 대출 상환 기간 채무 불이행률
    - DTI # 2
    - LTV
    - 로그 신용 점수
    - 신용 문제율
    - 부채 대비 신용 점수
    - 총 부채 비율
    - 월 소득 대비 부채 비율
    - 신용-부채 변화율
    - 근속 연수 대비 소득
    - 연체 발생 빈도
    - 최근 연체 위험 지표
    - 금융 위험 지수
    - 상환 속도
    - 자산 부족 정도
    - 재정 스트레스 지표 # 3
    - 단기 부채 위험
    - 과거 신용 위험 지표
    - 잔액 대비 상환 속도
    - 부채 증가 위험
    - 대출 목적_부채 부담
    - 신용 위험
    - 자산2 # 4
    - 자산3
    - 자산4
    - 월 소득 대비 대출 상환액 비율 # 5
    - 최대 신용한도 대비 사용 비율
    - 대출 금액 대비 연체 위험
    - 신용 점수 변화율
    - 신용 위험 가중치
    - 부채 비율 변화율
    - LTV 변화율
    - 신용 한도 대비 신용 사용률 변화
    - 최근 연체율
    - 신용 한도 대비 부채 부담
    - 월 저축 가능액
    - 연체 빈도 가중치
    - 연체 심각도 지수
    - 연체 후 회복력

  # statistical:
  #   - 주거 형태_연간 소득_mean #
  #   - 주거 형태_연간 소득_std
  #   - 주거 형태_연간 소득_min
  #   - 주거 형태_연간 소득_max
  #   - 주거 형태_현재 대출 잔액_mean #
  #   - 주거 형태_현재 대출 잔액_std
  #   - 주거 형태_현재 대출 잔액_min
  #   - 주거 형태_현재 대출 잔액_max
  #   - 주거 형태_월 상환 부채액_mean #
  #   - 주거 형태_월 상환 부채액_std
  #   - 주거 형태_월 상환 부채액_min
  #   - 주거 형태_월 상환 부채액_max
  #   - 주거 형태_신용 점수_mean #
  #   - 주거 형태_신용 점수_std
  #   - 주거 형태_신용 점수_min
  #   - 주거 형태_신용 점수_max
  #   - 대출 목적_연간 소득_mean #
  #   - 대출 목적_연간 소득_std
  #   - 대출 목적_연간 소득_min
  #   - 대출 목적_연간 소득_max
  #   - 대출 목적_현재 대출 잔액_mean #
  #   - 대출 목적_현재 대출 잔액_std
  #   - 대출 목적_현재 대출 잔액_min
  #   - 대출 목적_현재 대출 잔액_max
  #   - 대출 목적_월 상환 부채액_mean #
  #   - 대출 목적_월 상환 부채액_std
  #   - 대출 목적_월 상환 부채액_min
  #   - 대출 목적_월 상환 부채액_max
  #   - 대출 목적_신용 점수_mean #
  #   - 대출 목적_신용 점수_std
  #   - 대출 목적_신용 점수_min
  #   - 대출 목적_신용 점수_max
  #   - 대출 상환 기간_연간 소득_mean #
  #   - 대출 상환 기간_연간 소득_std
  #   - 대출 상환 기간_연간 소득_min
  #   - 대출 상환 기간_연간 소득_max
  #   - 대출 상환 기간_현재 대출 잔액_mean #
  #   - 대출 상환 기간_현재 대출 잔액_std
  #   - 대출 상환 기간_현재 대출 잔액_min
  #   - 대출 상환 기간_현재 대출 잔액_max
  #   - 대출 상환 기간_월 상환 부채액_mean #
  #   - 대출 상환 기간_월 상환 부채액_std
  #   - 대출 상환 기간_월 상환 부채액_min
  #   - 대출 상환 기간_월 상환 부채액_max
  #   - 대출 상환 기간_신용 점수_mean #
  #   - 대출 상환 기간_신용 점수_std
  #   - 대출 상환 기간_신용 점수_min
  #   - 대출 상환 기간_신용 점수_max

groups:
  주거:
    - 주거 형태
    - 주거 형태 채무 불이행률
  신용:
    - 신용 점수
    - 로그 신용 점수
    - 신용 거래 연수
    - 신용 문제율
    - 신용 문제 발생 횟수
    - 개설된 신용계좌 수
    - 부채 대비 신용 점수
    - 총 부채 비율
    - 월 소득 대비 부채 비율
    - 신용-부채 변화율
    - 신용 비율
    - DTI
    - LTV
    - 최대 신용한도 대비 사용 비율
    - LTV 변화율
    - 신용 점수 변화율
    - 신용 위험 가중치
    - 신용 한도 대비 신용 사용률 변화
    - 신용 한도 대비 부채 부담
  대출:
    - 대출 목적
    - 대출 상환 기간
    - 대출 상환 기간 채무 불이행률
    - 현재 대출 잔액
    - 현재 미상환 신용액
    - 월 상환 부채액
    - 대출 이자율
    - 대출 비율
    - 잔액 대비 상환 속도
    - 상환 속도
    - 대출 목적_고위험
    - 대출 목적_부채 부담
    - 대출 목적 채무 불이행률
    - 부채 비율 변화율
  직장/소득:
    - 연간 소득
    - 현재 직장 근속 연수
    - 근속 연수
    - 장기 근속 여부
    - 근속 연수 대비 소득
    - 월 소득 대비 대출 상환액 비율
  파산/연체:
    - 최근 연체 있음
    - 최근 연체 위험 지표
    - 연체 발생 빈도
    - 마지막 연체 이후 경과 개월 수
    - 개인 파산 횟수
    - 파산 경험 여부
    - 대출 금액 대비 연체 위험
    - 연체 후 회복력
    - 연체 빈도 가중치
    - 연체 심각도 지수
    - 최근 연체율
  금융위험:
    - 재정 스트레스 지표
    - 단기 부채 위험
    - 과거 신용 위험 지표
    - 부채 증가 위험
    - 금융 위험 지수
    - 자산 부족 정도
    - 신용 위험
  자산:
    - 자산
    - 체납 세금 압류 횟수
    - 최대 신용한도
    - 자산2
    - 자산3
    - 자산4
    - 월 저축 가능액
  # 통계:
  #   - 주거 형태_연간 소득_mean #
  #   - 주거 형태_연간 소득_std
  #   - 주거 형태_연간 소득_min
  #   - 주거 형태_연간 소득_max
  #   - 주거 형태_현재 대출 잔액_mean #
  #   - 주거 형태_현재 대출 잔액_std
  #   - 주거 형태_현재 대출 잔액_min
  #   - 주거 형태_현재 대출 잔액_max
  #   - 주거 형태_월 상환 부채액_mean #
  #   - 주거 형태_월 상환 부채액_std
  #   - 주거 형태_월 상환 부채액_min
  #   - 주거 형태_월 상환 부채액_max
  #   - 주거 형태_신용 점수_mean #
  #   - 주거 형태_신용 점수_std
  #   - 주거 형태_신용 점수_min
  #   - 주거 형태_신용 점수_max
  #   - 대출 목적_연간 소득_mean #
  #   - 대출 목적_연간 소득_std
  #   - 대출 목적_연간 소득_min
  #   - 대출 목적_연간 소득_max
  #   - 대출 목적_현재 대출 잔액_mean #
  #   - 대출 목적_현재 대출 잔액_std
  #   - 대출 목적_현재 대출 잔액_min
  #   - 대출 목적_현재 대출 잔액_max
  #   - 대출 목적_월 상환 부채액_mean #
  #   - 대출 목적_월 상환 부채액_std
  #   - 대출 목적_월 상환 부채액_min
  #   - 대출 목적_월 상환 부채액_max
  #   - 대출 목적_신용 점수_mean #
  #   - 대출 목적_신용 점수_std
  #   - 대출 목적_신용 점수_min
  #   - 대출 목적_신용 점수_max
  #   - 대출 상환 기간_연간 소득_mean #
  #   - 대출 상환 기간_연간 소득_std
  #   - 대출 상환 기간_연간 소득_min
  #   - 대출 상환 기간_연간 소득_max
  #   - 대출 상환 기간_현재 대출 잔액_mean #
  #   - 대출 상환 기간_현재 대출 잔액_std
  #   - 대출 상환 기간_현재 대출 잔액_min
  #   - 대출 상환 기간_현재 대출 잔액_max
  #   - 대출 상환 기간_월 상환 부채액_mean #
  #   - 대출 상환 기간_월 상환 부채액_std
  #   - 대출 상환 기간_월 상환 부채액_min
  #   - 대출 상환 기간_월 상환 부채액_max
  #   - 대출 상환 기간_신용 점수_mean #
  #   - 대출 상환 기간_신용 점수_std
  #   - 대출 상환 기간_신용 점수_min
  #   - 대출 상환 기간_신용 점수_max

model:
  type: "catboost"  # "xgboost", "lightgbm", "catboost" 중 선택
  random_state: 42
  xgboost:
    n_estimators: 1000
    learning_rate: 0.1
    max_depth: 5
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
  
  lightgbm:
    n_estimators: 1000
    learning_rate: 0.1
    num_leaves: 31
    max_depth: 5
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
  
  catboost:
    iterations: 1000
    learning_rate: 0.1
    depth: 5
    l2_leaf_reg: 3

train:
  test_size: 0.2
  n_splits: 5
  random_state: 42
  scaler: robust # minmax, standard, robust, maxabs, normalizer
  importance:
    use: False # True, False
    type: threshold # rank, threshold
    top-k: 65
    threshold: .005
  group:
    use: False # False
    value:
      - 주거
      - 신용
      - 대출
      - 직장/소득
      - 파산/연체
      - 금융위험
      - 자산
      # - 통계

exclude: 
  - 월 소득 대비 대출 상환액 비율 # 5
  - 최대 신용한도 대비 사용 비율
  - 대출 금액 대비 연체 위험
  - 신용 점수 변화율
  - 신용 위험 가중치
  - 부채 비율 변화율
  - LTV 변화율
  - 신용 한도 대비 신용 사용률 변화
  - 최근 연체율
  - 신용 한도 대비 부채 부담
  - 월 저축 가능액
  - 연체 빈도 가중치
  - 연체 심각도 지수
  - 연체 후 회복력
  - 현재 미상환 신용액
  # - 최근 연체 있음
  - 신용 위험

wandb:
  enabled: true  # wandb logging 활성화/비활성화
  project: "credit-default-prediction"  # wandb 프로젝트명

importance:
  개설된 신용계좌 수:  12.535037746257924
  현재 대출 잔액:  5.671902516477889
  대출 목적 채무 불이행률:  4.466511927576473
  연간 소득:  4.148266001019377
  신용 거래 연수:  3.5479897332252595
  로그 신용 점수:  3.376718450161678
  대출 목적_부채 통합:  3.365466818078205
  신용 점수:  3.248547152081639
  재정 스트레스 지표:  2.846052674129932
  자산:  2.4471345950207652
  잔액 대비 상환 속도:  2.3349686646093404
  연체 발생 빈도:  2.240826233957539
  금융 위험 지수:  2.2399281184902673
  과거 신용 위험 지표:  2.0496196642134348
  최대 신용한도:  2.0407870444865663
  최근 연체 위험 지표:  2.0057999542395355
  개인 파산 횟수:  1.9381124239048895
  대출 상환 기간 채무 불이행률:  1.8322953750893363
  자산4:  1.7970262672158313
  자산3:  1.7839731686601725
  자산2:  1.772761047415989
  LTV:  1.6257719510858744
  현재 직장 근속 연수:  1.60268338433662
  신용 문제율:  1.5981422590347494
  대출 상환 기간_장기 상환:  1.5977720668063276
  근속 연수 대비 소득:  1.5960657361714048
  주거 형태 채무 불이행률:  1.568858881434911
  마지막 연체 이후 경과 개월 수:  1.522404752109514
  총 부채 비율:  1.3958760333809461
  자산 부족 정도:  1.3718815878776498
  신용-부채 변화율:  1.2928744387292106
  신용 비율:  1.2383715936084088
  부채 대비 신용 점수:  1.16909013430754
  대출 이자율:  1.1141552924418487
  대출 목적_고위험:  1.1091885283628224
  신용 문제 발생 횟수:  1.0802837623951258
  근속 연수:  1.050934919910882
  대출 상환 기간_단기 상환:  1.0472213369762926
  월 상환 부채액:  1.001257766795939
  체납 세금 압류 횟수:  0.9943421868390371
  단기 부채 위험:  0.8609947675982712
  부채 증가 위험:  0.84658980840656
  신용 위험:  0.7222643526874752
  DTI:  0.6874920501573365
  월 소득 대비 부채 비율:  0.6708482640888946
  대출 비율:  0.6697020197207022
  대출 목적_부채 부담:  0.6205437372303565
  주거 형태_월세:  0.533621573964518
  상환 속도:  0.46427360155369546
  파산 경험 여부:  0.27404937121938927
  주거 형태_자가:  0.24580519870127482
  주거 형태_주택 담보 대출 (비거주 중):  0.1919149972839096
  최근 연체 있음:  0.11806380741353585
  장기 근속 여부:  0.09361763930229315
  대출 목적_주택 개보수:  0.07573738701405625
  주거 형태_주택 담보 대출 (거주 중):  0.0656893489550712
  대출 목적_사업 대출:  0.05230981564057606
  대출 목적_의료비:  0.03704110134366687
  대출 목적_여행 자금:  0.03440855287660547
  대출 목적_기타:  0.030362734790011402
  대출 목적_소규모 사업 자금:  0.01660100241411211
  대출 목적_고액 구매:  0.01533865301900132
  대출 목적_결혼 자금:  0.0058280257015514685
  대출 목적_자동차 구매:  0.0
  대출 목적_주택 구매:  0.0
  대출 목적_휴가 비용:  0.0
  대출 목적_교육비:  0.0
  대출 목적_이사 비용:  0.0
