data:
  train_path: './data/train.csv'
  test_path: './data/test.csv'
  submission_path: './data/sample_submission.csv'
  output_path: './data/submission'
  label_column: '채무 불이행 여부'

features:
  # 기본값을 사용하려면 아래 설정들을 생략해도 됩니다
  nominal_columns:
    - 주거 형태
    - 대출 목적
    - 대출 상환 기간
  
  ordinal_columns:
    - 현재 직장 근속 연수:
        - 1년 미만
        - 1년
        - 2년
        - 3년
        - 4년
        - 5년
        - 6년
        - 7년
        - 8년
        - 9년
        - 10년 이상

  # 참고용 numerical 컬럼들 (코드에서는 자동으로 계산됨)
  numerical_discrete:
    - 개설된 신용계좌 수
    - 신용 문제 발생 횟수
    - 마지막 연체 이후 경과 개월 수
    - 개인 파산 횟수
    - 신용 점수
    - 대출 목적_고위험
    - 근속 연수
    - 장기 근속 여부
    - 최근 연체 있음
    - 파산 경험 여부

  numerical_continuous:
    - 연간 소득
    - 체납 세금 압류 횟수
    - 신용 거래 연수
    - 최대 신용한도
    - 현재 대출 잔액
    - 현재 미상환 신용액
    - 월 상환 부채액
    - 자산 # 1
    - 대출 이자율
    - 대출 비율
    - 신용 비율
    - 주거 형태 채무 불이행률
    - 대출 목적 채무 불이행률
    - 대출 상환 기간 채무 불이행률
    - DTI # 2
    - LTV
    - 로그 신용 점수
    - 신용 문제율
    - 부채 대비 신용 점수
    - 총 부채 비율
    - 월 소득 대비 부채 비율
    - 신용-부채 변화율
    - 근속 연수 대비 소득
    - 연체 발생 빈도
    - 최근 연체 위험 지표
    - 금융 위험 지수
    - 상환 속도
    - 자산 부족 정도
    - 재정 스트레스 지표 # 3
    - 단기 부채 위험
    - 과거 신용 위험 지표
    - 잔액 대비 상환 속도
    - 부채 증가 위험
    - 대출 목적_부채 부담
    - 신용 위험

groups:
  주거:
    - 주거 형태
    - 주거 형태 채무 불이행률
  신용:
    - 신용 점수
    - 로그 신용 점수
    - 신용 거래 연수
    - 신용 문제율
    - 신용 문제 발생 횟수
    - 개설된 신용계좌 수
    - 부채 대비 신용 점수
    - 총 부채 비율
    - 월 소득 대비 부채 비율
    - 신용-부채 변화율
    - 신용 비율
    - DTI
    - LTV
  대출:
    - 대출 목적
    - 대출 상환 기간
    - 대출 상환 기간 채무 불이행률
    - 현재 대출 잔액
    - 현재 미상환 신용액
    - 월 상환 부채액
    - 대출 이자율
    - 대출 비율
    - 잔액 대비 상환 속도
    - 상환 속도
    - 대출 목적_고위험
    - 대출 목적_부채 부담
    - 대출 목적 채무 불이행률
  직장/소득:
    - 연간 소득
    - 현재 직장 근속 연수
    - 근속 연수
    - 장기 근속 여부
    - 근속 연수 대비 소득
  파산/연체:
    - 최근 연체 있음
    - 최근 연체 위험 지표
    - 연체 발생 빈도
    - 마지막 연체 이후 경과 개월 수
    - 개인 파산 횟수
    - 파산 경험 여부
  금융위험:
    - 재정 스트레스 지표
    - 단기 부채 위험
    - 과거 신용 위험 지표
    - 부채 증가 위험
    - 금융 위험 지수
    - 자산 부족 정도
    - 신용 위험
  자산:
    - 자산
    - 체납 세금 압류 횟수
    - 최대 신용한도

model:
  type: "catboost"  # "xgboost", "lightgbm", "catboost" 중 선택
  random_state: 42
  xgboost:
    n_estimators: 1000
    learning_rate: 0.1
    max_depth: 5
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
  
  lightgbm:
    n_estimators: 1000
    learning_rate: 0.1
    num_leaves: 31
    max_depth: 5
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
  
  catboost:
    iterations: 1000
    learning_rate: 0.1
    depth: 5
    l2_leaf_reg: 3

train:
  test_size: 0.2
  n_splits: 5
  random_state: 42
  scaler: robust # minmax, standard, robust, maxabs, normalizer
  importance:
    use: False # True, False
    type: threshold # rank, threshold
    top-k: 70
    threshold: .01
  group: 
    use: True # False
    value:
      - 주거
      - 신용
      - 대출
      - 직장/소득
      - 파산/연체
      - 금융위험
      - 자산

wandb:
  enabled: true  # wandb logging 활성화/비활성화
  project: "credit-default-prediction"  # wandb 프로젝트명

importance:
  개설된 신용계좌 수: 12.23746589641173
  현재 대출 잔액: 6.707812424321284
  현재 미상환 신용액: 5.138501433441112
  대출 목적 채무 불이행률: 4.597933383345642
  연간 소득: 4.148845485637612
  로그 신용 점수: 3.7480897420680943
  신용 거래 연수: 3.449487282998617
  신용 점수: 3.3522914160185717
  대출 목적_부채 통합: 3.3427326632561947
  최대 신용한도: 3.1021734633720133
  자산: 2.758198760263638
  재정 스트레스 지표: 2.3538559141726942
  신용 문제율: 2.2439233986246117
  과거 신용 위험 지표: 2.178454142777963
  개인 파산 횟수: 1.8859601609843963
  최근 연체 위험 지표: 1.8821393035171423
  대출 상환 기간_단기 상환: 1.8667060781587608
  대출 상환 기간_장기 상환: 1.814194516881728
  LTV: 1.772169245779966
  금융 위험 지수: 1.6473395686291172
  자산 부족 정도: 1.6096827731899923
  현재 직장 근속 연수: 1.599132487707572
  근속 연수 대비 소득: 1.4594207396423984
  총 부채 비율: 1.4447635314786105
  연체 발생 빈도: 1.4228380313709237
  신용 비율: 1.4055445545330045
  근속 연수: 1.3560507957624672
  마지막 연체 이후 경과 개월 수: 1.3515728220694105
  부채 증가 위험: 1.334713064394316
  신용-부채 변화율: 1.3222672034994054
  대출 상환 기간 채무 불이행률: 1.2528251913233674
  월 상환 부채액: 1.1947558052790082
  부채 대비 신용 점수: 1.165140426985267
  주거 형태 채무 불이행률: 1.1552366308167894
  신용 문제 발생 횟수: 1.129501381978926
  대출 목적_고위험: 1.0849479431938278
  주거 형태_월세: 0.9665470693948406
  단기 부채 위험: 0.9226083482171862
  체납 세금 압류 횟수: 0.887813502792558
  대출 이자율: 0.8512355786071564
  신용 위험: 0.8353088586679984
  상환 속도: 0.7207060268744958
  대출 목적_부채 부담: 0.6618557944174446
  대출 비율: 0.5632574789965288
  DTI: 0.419911725188415
  월 소득 대비 부채 비율: 0.4013477053585521
  파산 경험 여부: 0.322094071702808
  주거 형태_자가: 0.2583604916487797
  주거 형태_주택 담보 대출 (거주 중): 0.17146492638839456
  장기 근속 여부: 0.1364651645936178
  주거 형태_주택 담보 대출 (비거주 중): 0.11946768378918175
  대출 목적_기타: 0.07556878792140545
  대출 목적_사업 대출: 0.060933345482147225
  대출 목적_자동차 구매: 0.044888489145603366
  대출 목적_소규모 사업 자금: 0.03520453907827429
  대출 목적_의료비: 0.019861986349953675
  대출 목적_결혼 자금: 0.004295316440030982
  대출 목적_고액 구매: 0.002200132020039397
  대출 목적_휴가 비용: 0.0019353130384233233
  최근 연체 있음: 0.0
  대출 목적_주택 구매: 0.0
  대출 목적_교육비: 0.0
  대출 목적_이사 비용: 0.0
  대출 목적_여행 자금: 0.0
  대출 목적_주택 개보수: 0.0