data:
  train_path: './data/train.csv'
  test_path: './data/test.csv'
  submission_path: './data/sample_submission.csv'
  output_path: './data/submission'
  label_column: '채무 불이행 여부'

features:
  # 기본값을 사용하려면 아래 설정들을 생략해도 됩니다
  nominal_columns:
    - 주거 형태
    - 대출 목적
    - 대출 상환 기간
  
  ordinal_columns:
    - 현재 직장 근속 연수:
        - 1년 미만
        - 1년
        - 2년
        - 3년
        - 4년
        - 5년
        - 6년
        - 7년
        - 8년
        - 9년
        - 10년 이상

  # 참고용 numerical 컬럼들 (코드에서는 자동으로 계산됨)
  numerical_discrete:
    - 개설된 신용계좌 수
    - 신용 문제 발생 횟수
    - 마지막 연체 이후 경과 개월 수
    - 개인 파산 횟수
    - 신용 점수
    - 대출 목적_고위험
    - 근속 연수
    - 장기 근속 여부
    - 최근 연체 있음
    - 파산 경험 여부
    - 신용 점수 등급

  numerical_continuous:
    - 연간 소득
    - 체납 세금 압류 횟수
    - 신용 거래 연수
    - 최대 신용한도
    - 현재 대출 잔액
    - 현재 미상환 신용액
    - 월 상환 부채액
    - 자산
    - 대출 이자율
    - 대출 비율
    - 신용 비율
    - 주거 형태 채무 불이행률
    - 대출 목적 채무 불이행률
    - 대출 상환 기간 채무 불이행률
    - DTI
    - LTV
    - 로그 신용 점수
    - 신용 문제율
    - 부채 대비 신용 점수
    - 총 부채 비율
    - 월 소득 대비 부채 비율
    - 신용-부채 변화율
    - 근속 연수 대비 소득
    - 연체 발생 빈도
    - 최근 연체 위험 지표
    - 금융 위험 지수
    - 상환 속도
    - 자산 부족 정도
    - 재정 스트레스 지표
    - 단기 부채 위험
    - 과거 신용 위험 지표
    - 잔액 대비 상환 속도
    - 부채 증가 위험
    - 대출 목적_부채 부담
    - 신용 위험


model:
  type: "catboost"  # "xgboost", "lightgbm", "catboost" 중 선택
  random_state: 42
  xgboost:
    n_estimators: 1000
    learning_rate: 0.1
    max_depth: 5
    min_child_weight: 1
    subsample: 0.8
    colsample_bytree: 0.8
  
  lightgbm:
    n_estimators: 1000
    learning_rate: 0.1
    num_leaves: 31
    max_depth: 5
    min_child_samples: 20
    subsample: 0.8
    colsample_bytree: 0.8
  
  catboost:
    iterations: 1000
    learning_rate: 0.1
    depth: 5
    l2_leaf_reg: 3

train:
  test_size: 0.2
  n_splits: 5
  random_state: 42

wandb:
  enabled: true  # wandb logging 활성화/비활성화
  project: "credit-default-prediction"  # wandb 프로젝트명
